name: Version Bump

on:
  push:
    branches: [ test ]

jobs:

  # Bumps the patch version 0.0.x on the dev branch when new code hits test
  bump-version-number:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: 'actions/checkout@v2'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 'Concatenate package.json'
        run: cat ./package.json

      - name: 'Fetch dev branch'
        run: git fetch origin dev

      - name: 'Bump version number on dev'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          default: patch
          commit-message: 'chore: bump version to {{version}}'
          tag-prefix: 'v'
          target-branch: 'dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Concatenate package.json'
        run: cat ./package.json
